language: android

sudo: false

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
 cache:
   directories:
   - "$HOME/.gradle"
   before_install:
   - chmod +x gradlew
script:
  - "./gradlew assembleRelease"
