language: android

sudo: false

android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
  - extra-android-support
jdk: oraclejdk8
cache:
   directories:
   - "$HOME/.gradle"

before_install:
   - chmod +x gradlew

script:
  - "./gradlew publishApkDebug"
  - "./gradlew assembleRelease"

deploy:
    provider: releases
    api_key: affd4f8ae3500a6ba3deb5bcbfc740f538603f6f
    file: statepage\build\outputs\aar\statepage-release.aar
    skip_cleanup: true
    on:
      tags: true

